### ISSUE TITLE
Add failure case test 

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/clearpass-api#5]
## Context

`test_connectivity` failure test is empty, at the moment.
We should remove it, or craft a 4xx / 5xx error code cassette to test with.

Task List:

- [x] Copy the successful cassette and change the 2xx to a 4xx/5xx error code
- [x] Rerun the failing test to be sure behaving (NOT recording)

**Comment by zdc217** [comment]
Blocked by #6. The project needs some resources for local development. It's missing a Makefile and requirements-dev.in at least. Those items are planned in #6.

**Comment by mpitcel** [comment]
> Blocked by #6. The project needs some resources for local development. It's missing a Makefile and requirements-dev.in at least. Those items are planned in #6.

Started adding items for #6 : https://github.com/techservicesillinois/clearpass-api/pull/8

**Comment by edthedev** [comment]
Unblocked as #6 is completed.

**Comment by zdc217** [comment]
We were able to create a failed request cassette, but when we run the test suite, both tests fail
```
FAILED tests/test_connector.py::test_connectivity - assert False
FAILED tests/test_connector.py::test_failed_connectivity - assert False
ERROR tests/test_connector.py::test_connectivity - AssertionError: Only played back 1 responses
ERROR tests/test_connector.py::test_failed_connectivity - AssertionError: Only played back 1 responses
```
Both tests are calling `test_connectivity` in the client code and we are not sure if that is the problem or if it's something else.
