### ISSUE TITLE
Add MyPy stubs

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/clearpass-api#6]
## Context

When we import this library from our ClearPass SOAR app, our CI/CD test suite gives a MyPy warning.

Task List:

- [ ] Add a Makefile 
- [ ] Add MyPy to the test step in the Makefile 
- [ ] Add type declarations until the tests pass 
- [ ] Remove the MyPy Exception from the SOAR ClearPass App and retest

**Comment by mpitcel** [comment]
This issue blocks #5
